name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone repository
        run: git clone https://github.com/EricZeller/flutter-world-clock-v2.git flutter_app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5' # deine gewünschte Version

      - name: Get dependencies
        run: cd flutter_app && flutter pub get

      - name: Build web 
        run: cd flutter_app && flutter build web --release
      
      - name: Push build/web to Repo A
        run: |
          cd flutter_app/build/web
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Flutter Web build"
          git push --force https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/EricZeller/world-clock-v2-wev.git main


